name: TravelX
description: Advanced Trip Capture app (modular, failproof detection, offline-first)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.5
  fl_chart: ^1.1.1
  google_maps_flutter: ^2.7.0
  url_launcher: ^6.1.10
  collection: ^1.18.0
  flutter_map: ^8.2.2     # Stable for Flutter 3.7
  latlong2: ^0.9.1         # Compatible with flutter_map 3.x

  # Sensors / Location / Connectivity
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  sensors_plus: ^7.0.0
  flutter_blue_plus: ^1.4.0
  connectivity_plus: ^6.0.3
  flutter_activity_recognition: ^4.0.0
  permission_handler: ^12.0.1

  # Notifications / Vibration
  #flutter_local_notifications: ^19.4.2
  #vibration: ^1.9.0
  flutter_local_notifications: ^19.4.2
  vibration: ^3.1.4 

  # Data / Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  # flutter_blue_advertiser: ^2.0.0

  flutter_ble_peripheral: ^1.2.1
  convert: ^3.1.1
    # Add these for Firebase and Google Auth
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1

  # Network / Utils
  http: ^1.5.0
  uuid: ^4.1.0
  crypto: ^3.0.2   # Compatible with Flutter 3.7
  flutter_svg: ^2.2.1
  encrypt: ^5.0.3 # Added for encryption
  pointycastle: ^3.7.4
  asn1lib: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true
  assets:
    - .env # Add this line

platforms:
  android:
  ios:
  web:
