// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGy_0TR1GBLb7ZiOvkZvY9_DY-2DBfabA',
    appId: '1:969091346696:web:72990e832e28d12d937cbd',
    messagingSenderId: '969091346696',
    projectId: 'travelx-45a54',
    authDomain: 'travelx-45a54.firebaseapp.com',
    storageBucket: 'travelx-45a54.firebasestorage.app',
    measurementId: 'G-DE3WEDMEME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7B1nwydPK01rN34B9VDHu1pkD-7KFyM',
    appId: '1:969091346696:android:7b7deba8085c323a937cbd',
    messagingSenderId: '969091346696',
    projectId: 'travelx-45a54',
    storageBucket: 'travelx-45a54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyyLP3lcP9ZgmAmMqb4rWZf66KVqtmKIc',
    appId: '1:969091346696:ios:7db48f58654ac8bb937cbd',
    messagingSenderId: '969091346696',
    projectId: 'travelx-45a54',
    storageBucket: 'travelx-45a54.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyyLP3lcP9ZgmAmMqb4rWZf66KVqtmKIc',
    appId: '1:969091346696:ios:c9c4c96e39ad9c5d937cbd',
    messagingSenderId: '969091346696',
    projectId: 'travelx-45a54',
    storageBucket: 'travelx-45a54.firebasestorage.app',
    iosBundleId: 'com.example.mvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGy_0TR1GBLb7ZiOvkZvY9_DY-2DBfabA',
    appId: '1:969091346696:web:e92eff2ddd01bbb2937cbd',
    messagingSenderId: '969091346696',
    projectId: 'travelx-45a54',
    authDomain: 'travelx-45a54.firebaseapp.com',
    storageBucket: 'travelx-45a54.firebasestorage.app',
    measurementId: 'G-TT9Z6JTWG1',
  );
}
