import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart'; // Import Firebase Core
import 'package:firebase_auth/firebase_auth.dart'; // Import Firebase Auth

import 'firebase_options.dart'; // Generated by FlutterFire
import 'app.dart';
import 'services/storage_service.dart';
import 'services/notification_service.dart';
import 'services/permission_service.dart';
import 'services/sync_service.dart';
import 'services/gps_service.dart';
import 'services/accel_service.dart';
import 'services/bluetooth_service.dart';
import 'services/activity_service.dart';
import 'services/detection_service.dart';
import 'services/auth_service.dart'; // Import your new Auth Service
import 'screens/auth_wrapper.dart'; // Import the new Auth Wrapper

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // --- Initialize Firebase FIRST ---
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await PermissionService.requestAll();
  await StorageService.init();
  await NotificationService.init();

  SyncService.initialize();

  final gps = GpsService();
  final accel = AccelService();
  final bt = BluetoothService();
  final activity = ActivityService();

  final detection = DetectionService(
    gps: gps,
    accel: accel,
    bt: bt,
    activity: activity,
  );

  runApp(
    MultiProvider(
      providers: [
        // Provide the AuthService
        Provider<AuthService>(create: (_) => AuthService()),
        // Provide the stream of User objects
        StreamProvider<User?>.value(
          value: AuthService().authStateChanges,
          initialData: null,
        ),
        Provider<GpsService>.value(value: gps),
        Provider<AccelService>.value(value: accel),
        Provider<BluetoothService>.value(value: bt),
        Provider<ActivityService>.value(value: activity),
        Provider<DetectionService>.value(value: detection),
        Provider<SyncService>.value(value: SyncService.instance),
      ],
      child: const TripApp(),
    ),
  );
}